Fix failing command due to missing .gitignore file
The script currently fails when running due to a missing `.gitignore`
file in the built package.

  % npx create-replicate@latest my-image-interrogator --model=yorickvp/llava-13b:2cfef05a8e8e648f6e92ddb53fa21a81c04ab2c4f1390a6528cc4e331d608df8
  Creating project "my-image-interrogator"...
  Model: yorickvp/llava-13b:2cfef05a8e8e648f6e92ddb53fa21a81c04ab2c4f1390a6528cc4e331d608df8...
  Copying files...
  node:fs:3003
    binding.copyFile(
            ^

  Error: ENOENT: no such file or directory, copyfile '/Users/Aron/.npm/_npx/f6f080e244bc31d2/node_modules/create-replicate/template/.gitignore' -> '/Users/Aron/Code/my-image-interrogator/.gitignore'
      at Object.copyFileSync (node:fs:3003:11)
      at file:///Users/Aron/.npm/_npx/f6f080e244bc31d2/node_modules/create-replicate/index.mjs:52:4 {
    errno: -2,
    code: 'ENOENT',
    syscall: 'copyfile',
    path: '/Users/Aron/.npm/_npx/f6f080e244bc31d2/node_modules/create-replicate/template/.gitignore',
    dest: '/Users/Aron/Code/my-image-interrogator/.gitignore'
  }

  Node.js v20.10.0

So we now explicitly set the `files` key in the package.json to ensure
that it is included and that we don't include all the other dev files.